# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# User.destroy_all
# User.create([
# {name: "Adam B", email: "adam@example.com", age: "20", zip_code: 20037},
# {name: "Brenda C", email: "brenda@example.com", age: "22", zip_code: 20036},
# {name: "Catherine D", email: "catherine@example.com", age: "20", zip_code: 20035},
# {name: "Donald E", email: "donald@example.com", age: "23", zip_code: 20034}
# ])
Guide.destroy_all
Guide.create([
{cleaning_area: "Floors", cleaning_guide: "Guide (for ceramic tile floors) - First, sweep the floor thoroughly. Don’t forget the corners and under the edges of appliances. Next, fill the bucket with warm water. Add dish detergent if there are sticky or greasy spots on the floor. Otherwise, warm water should work just fine.Mop or sponge the floor, rinsing frequently. Allow floor to dry before use. Source - http://www.howtocleanstuff.net/"},
{cleaning_area: "Windows", cleaning_guide: "Guide (for acrylic windows) - Begin by determining how strong of a cleaning solution is needed by observing the amount of dirt present. If there is just a small amount of dust, then water is sufficient. If there is more significant dirt build up, such as outside-facing windows, then you may wish to mix in a mild, non-abrasive detergent with the water. If the surface has just a small amount of dirt, use a soft cloth moistened with water to gently wipe it away. Turn the cloth often to keep a clean side on the glass. It’s important to avoid rubbing the dirt on the surface because it can cause more scratching. For more significant amounts of dirt, use a cloth that is very wet with water. Gently swab the cloth on the surface and allow the water to lift the dirt and “rinse” it away. Once most of the dirt has been removed with the water, use a second cloth to clean the glass. Source - http://www.howtocleanstuff.net/"},
{cleaning_area: "Bathroom", cleaning_guide: "Guide - Clear bathroom counters. Put away all toiletries, makeup and hair supplies. Unplug any appliances. Liberally spray shower and tub with mildew- and soap scum-removing cleaner. Squirt toilet bowl cleaner in the bowl of the toilet, making sure to get all the way under and around the rim. Spray the sink and countertop with bathroom cleaner. Brush to scrub shower walls and bathtub. Let it sit. Fill the sink with a few inches of hot water. Wipe down sink using a wet cloth and countertop well. Drain the sink and dry it and the counter with a clean rag. Use toilet brush to scrub the inside bowl of the toilet, then around rim, seat and lid. Use the wet and dry rags from cleaning the sink to first wipe down the entire toilet, and then wipe it dry. Flush. To clean the tub: Drain the tub. Fill your bucket with warm water, and then dump along the sides of the shower wall to rinse off the cleaner. Once the shower walls have been rinsed well, wipe down the entire shower and tub with a large dry rag. Mirrors:  Spray mirrors with glass cleaner, then use a lint-free cloth or newsprint to wipe clean for a streak-free shine. Sweep up dust and debris from the floor. Source - https://www.pgeveryday.com/home-garden/cleaning-organization/article/how-to-clean-your-bathroom-in-30-minutes-or-less"},
{cleaning_area: "Fixtures", cleaning_guide: "Guide: Chandeliers: Dust your crystal chandeliers weekly, especially during pollen season. But once or twice a year, wash them.  If the chandelier isn’t too big, take it down and lay it on top of a towel spread on a table. If it’s huge, hire a handyman to bring it down, or grab a stepladder and clean it while it hangs. Take a picture of the chandelier before you start cleaning. That way you’ll remember where each crystal belongs if you take them off during cleaning. Mix a solution of 1 ounce mild dish soap with ¼ cup white vinegar and 3 cups water. Using a spray bottle, spritz each crystal.  Let dry and polish with a microfiber cloth. For light bulbs: Turn off electricity to the bulb. Wipe thoroughly with a dry cloth is the best way to get rid of dust and dirt. Source - http://www.houselogic.com/home-advice/lighting/clean-room-light-fixtures/"},
{cleaning_area: "House Appliances", cleaning_guide: "Guide: Cabinet fronts:  Wipe from top to bottom using a microfiber cloth dampened with water and a few drops of mild cleanser, follow the direction of the grain. Rinse the cloth and repeat. Stovetops: Scour the surface using a microfiber cloth moistened with water and cleaner.  Countertops: Clean the countertops with a microfiber cloth. Wet it with water and mild cleaner, and wipe the countertops using a circular motion. Then mist with water and wipe down with a clean cloth. Wash the tile backsplash using the same method. Sinks: Scrub in a circular motion from the top to the drain with a cloth and cleaner. Use an old toothbrush to remove any mold lurking in the edges of the drain or faucet. Rinse the area. Dish racks: Soak in a sink filled with water and a little dishwashing liquid. Scrub off food particles with an old toothbrush. Dry with a clean cloth."}
])

